### ISSUE TITLE
delete of shared GLObjects when Drawable is released

### ISSUE THREAD

**Issue by mp3butcher** [openscenegraph/OpenSceneGraph#674]
Introduced when trying to fix VAO leak  https://github.com/openscenegraph/OpenSceneGraph/pull/587#issuecomment-412280987
commit engaged:
https://github.com/openscenegraph/OpenSceneGraph/commit/eee5d5482e41290e7c210273f8c6bae489cedb76
To reproduce
```
osgViewer::Viewer viewer;
if(wantmorebug) //rise another crash at program end with OSG_VERTEX_BUFFER_HINT=VAO
    viewer.setThreadingModel(osgViewer::Viewer::DrawThreadPerContext);
osg::Geometry * geom= osg::createTexturedQuadGeometry(osg::Vec3f(-0.5,-0.5,-0.5),osg::Vec3f(1,0,0),osg::Vec3f(0,0,1));
geom->setUseVertexBufferObjects(true);
osg::Geometry *  geom2=(osg::Geometry*)geom->clone(osg::CopyOp::SHALLOW_COPY);
   osg::Group *gr=new osg::Group;
   gr->addChild(geom);
   gr->addChild(geom2);

   viewer.setSceneData(gr);
   viewer.realize();
   viewer.frame();//for the fun as GLObjectVisitor already have done its stuff

    //assume contextid==0
    int contextid=   0;
    OSG_WARN<<"BufferObject uploaded suppose ok at frame 0:"<<
             ( geom->getVertexArray()->getVertexBufferObject()->getGLBufferObject(contextid) ?
                   "OK" : "BAD!!!!!!!!!" )<<std::endl;
    //remove  geom2 (no more ref to it)
    gr->removeChild(1);
    OSG_WARN<<"BufferObject uploaded suppose ok at  preframe 1:"<<
              ( geom->getVertexArray()->getVertexBufferObject()->getGLBufferObject(contextid) ?
                    "OK" : "BAD!!!!!!!!!" )<<std::endl;
    viewer.frame();
    OSG_WARN<<"BufferObject uploaded suppose ok at postframe 1:"<<
              ( geom->getVertexArray()->getVertexBufferObject()->getGLBufferObject(contextid) ?
                    "OK" : "BAD!!!!!!!!!" )<<std::endl;
viewer.run();
```

**Comment by mp3butcher** [comment]
commenting out Geometry::releasGLObject in ~Geoemtry seams enough but ...I'd like to be sure

**Comment by mp3butcher** [comment]
Think I found the crash related to threadingmodel:
GLExtensions may be destroyed when VertexArrayStateManager is purged

**Comment by openscenegraph** [comment]
I have resolved the issue by refactoring the Geometry destructor so that is just resets the local array and primitives ref_ptr<>'s + arrays and relies upon the Array/PrimitiveSet/BufferData destructors for doing release of GL objects from within their own destructors.  This means that the shared arrays/primitives don't get released prematurely.

https://github.com/openscenegraph/OpenSceneGraph/commit/337f24051bc06829ba240b4cb38580f5fae20e7e

**Comment by openscenegraph** [comment]
@JDGBOLT Could you confirm which fix is working for you?  The fix that I checked (https://github.com/openscenegraph/OpenSceneGraph/commit/337f24051bc06829ba240b4cb38580f5fae20e7e) in or @mp3butcher's PR?

**Comment by JDGBOLT** [comment]
Sorry, the fix that you checked in (337f240) seemed to work correctly as near as I can tell, as far as eliminating the crashing problem I have had. But I can't say for sure whether or not whether there are other problems relating to the VAS system that mp3butcher pointed out. At least one other user also mentioned that it seemed to fix his crashing, so hopefully it is resolved on the OpenMW side, but can't say for sure without testing from other users.

**Comment by mp3butcher** [comment]
@openscenegraph 
i haven't checked but the wantmorebug path of the provided code may still crash if i'm right.
This threading issue come from the fact that VAS may be freed from a rendering thread that have already killed its context (and so on it VASmanager)....
I already described in my pr https://github.com/openscenegraph/OpenSceneGraph/pull/677 how this could be fixed (registering created vas in vas manager and kill them with the context destruction)
